[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "PWSQC-py"
version = "0.0.0"
dependencies = [
    "numpy",
    "pandas",
    "geopy",
]
requires-python = ">=3.11"
authors = [
    { name = "Lotte de Vos", email = "lotte.devos@wur.nl" },
    { name = "Jonas Kittner", email = "jonas.kittner@rub.de" }
]
maintainers = [{ name = "Jonas Kittner", email = "jonas.kittner@rub.de" }]
description = "Quality control for crowdsourced personal weather station rainfall data"
readme = "README.md"
license = "CC-BY-SA-4.0"
license-files = ["LICENSE*"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
]

[project.urls]
Homepage = "https://github.com/RUBclim/pwsqc-py"
Documentation = "https://rubclim.github.io/pwsqc-py/"
Repository = "https://github.com/RUBclim/pwsqc-py"

[project.optional-dependencies]
polars = ["polars"]
dev = [
    "polars",
    "pytest",
    "coverage",
    "covdefaults",
    "furo",
    "myst_parser",
    "pytest-randomly",
    "sphinx<9",
    "sphinx-copybutton",
    "sphinx-toolbox",
    "sphinx_autodoc_typehints",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = { find = { where = ["src"], include = ["pwsqc*"]}}

[tool.coverage.report]
fail_under = 100
omit = ["*/main.py"]

[tool.coverage.run]
parallel = true
plugins = ["covdefaults"]
source_pkgs = ["pwsqc"]

[tool.autopep8]
max_line_length = 88

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_unreachable = true
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true

[[tool.mypy.overrides]]
module = ["tests.*", "testing.*"]
disallow_untyped_defs = false
disallow_incomplete_defs = false

[[tool.mypy.overrides]]
module = ["geopy.*"]
ignore_missing_imports = true
